version: "3"

services:
  sensor_module:
    build: ./sensor_module
    ports:
      - "8883:8883"
      - "5683:5683"
    networks:
      - coap_network
    environment:
      - COAP_URL=sensor_module

  server_module:
    build: ./server_module
    ports:
      - "8000:8000"
    networks:
      - coap_network
    depends_on:
      - sensor_module
    environment:
      - COAP_URL=coap://sensor_module:5683

networks:
  coap_network:
    driver: bridge
